version: '3'
services:
  app-service:
    container_name: app-container
    build: .
    ports:
      - 8081:8081
    restart: on-failure
    depends_on:
      - mysql-service
    networks:
      - backend
  mysql-service:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    expose:
      # Opens port 3306 on the container
      - '3306'
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - backend
  phpmyadmin-service:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    depends_on:
      - mysql-service
    environment:
      - PMA_HOST=mysql-service
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - backend
volumes:
  mysql_volume:
networks:
  backend:
    driver: bridge
